Add Pyramid 2.0 compatibility
Pylons/pyramid_ldap pull request #33
Opened 2021-05-03 21:58 UTC by msander

- replace pyramid.compat by six
- replace set_request_property by add_request_method

fixes #32 and #26

2021-05-04 00:08 UTC, bertjwregeer commented
Pyramid 2.0 is strictly Python 3, replacing `pyramid.compat` with `six` seems a bit silly. In most cases we can rely on `b` prefixes where necessary.

2021-05-04 00:52 UTC, stevepiercy requested changes

2021-05-04 00:52 UTC, stevepiercy commented on pyramid_ldap/__init__.py
> +        included the domain (e.g. CORP\\exampleuser) would raise
This should be a literal.
```suggestion
        included the domain (e.g., ``CORP\exampleuser``) would raise
```

2021-05-04 00:52 UTC, stevepiercy commented on pyramid_ldap/__init__.py
> +        ``ldap.FILTER_ERROR`` because the ``\\`` led to an invalid search
Please revert.
```suggestion
        ``ldap.FILTER_ERROR`` because the ``\`` led to an invalid search
```

2021-05-04 00:52 UTC, stevepiercy commented on pyramid_ldap/__init__.py
> +        "CORP\\exampleuser"). Applications using pyramid_ldap can preprocess
This should also be a literal.

```suggestion
        ``CORP\exampleuser``). Applications using pyramid_ldap can preprocess
```

2021-05-04 00:53 UTC, stevepiercy commented
@bertjwregeer should we drop EOLed Pythons and add supported versions, as well as move this to GitHub Actions?

2021-05-04 01:24 UTC, bertjwregeer commented
Yes, this extension needs a lot of love as it has received none over the years, but just dropping Py2 support and matching Pyramid 2.0 would be a good start.

2021-05-04 03:10 UTC, stevepiercy commented
@bertjwregeer how should we proceed? We could do it all in one swoop—fixing bugs, dropping EOLed Pythons, moving to GHA, and adding Pyramid 2.0 compat—or do it in baby steps to cut two or more releases. I can do the work, just need advice and direction.

2021-05-04 07:23 UTC, msander commented
> Pyramid 2.0 is strictly Python 3, replacing `pyramid.compat` with `six` seems a bit silly. In most cases we can rely on `b` prefixes where necessary.

Pyramid 2.0 compatibility does not mean that you need to drop Pyramid 1.x compatibility (which supports Python 2). 
However, Python 2 is EOL and I have not touched any Python 2 projects in years. So I guess it would be a reasonable decision.
If you want, I can modify my pull request and remove `six`.

2021-05-04 08:26 UTC, stevepiercy approved these changes
Thank you!

2021-05-04 08:45 UTC, msander commented
> Thank you for the docstring changes!

Thank you for you review.

However, PEP8 is failing again due to these changes:

```
pyramid_ldap/__init__.py:132:42: W605 invalid escape sequence '\e'
pyramid_ldap/__init__.py:133:45: W605 invalid escape sequence '\`'
pyramid_ldap/__init__.py:137:15: W605 invalid escape sequence '\e'
```
Don't we need double backslashes here?

2021-05-04 10:41 UTC, stevepiercy commented
Flake8 gives a false positive. This is a reStructuredText inline literal, but Flake8 does not interpret it as such. See screenshot for how it renders to HTML with the changes I requested and which you applied.

![Screen Shot 2021-05-04 at 3 15 42 AM](https://user-images.githubusercontent.com/102112/116989903-3bdf8980-ac87-11eb-9118-634e2b5fb2c5.png)

I could not find in PEP8 that it covers this edge case. To avoid the Flake8 warning, change the last line of the docstring to ignore this warning:

```
"""  # noqa: W605
```

Also I missed a couple of changes in `tests.py` that should have the same `  # noqa: W605`:

```
pyramid_ldap/tests.py:206:31: W605 invalid escape sequence '\l'
pyramid_ldap/tests.py:216:40: W605 invalid escape sequence '\*'
```

...would avoid the warning, pass tests, and not obscure the original intent of the test:

```python
        inst.authenticate('BAD\login', 'password')  # noqa: W605
#...
        inst.authenticate('login', 'bad\*()password')  # noqa: W605
```

2021-05-04 13:12 UTC, msander commented
Thank you for your explanation. 
Nevertheless, I think the double backslash is the correct solution.
The alternative would be to use a raw string (r"...").
An invalid escape like "\*" is currently interpreted as "\\*", but will result in a SyntaxError in the future. That's what the warning is about.

https://www.flake8rules.com/rules/W605.html

Also the tests are correct and finally pass with the double backslash.

The documentation is also rendered the same.

2021-05-05 07:58 UTC, stevepiercy commented
OK, thank you for explaining. I misunderstood. I apologize for my mistake.

We have two failed build jobs, one of which is an allowed failure for Python 3.7 and the other for a false positive that coverage is below 100%. We can skip the Python 3.7 failure for now, but we need to resolve the coverage issue. I've seen this issue in other repos. I'll look for how we fixed it. [It was working just prior to this PR](https://travis-ci.com/github/Pylons/pyramid_ldap/builds/197640295).

2021-05-05 08:23 UTC, stevepiercy commented
When I run `tox -r -e py2-cover,py3-cover,coverage` locally, it passes. I checked closely in the Travis log, and noticed ["Cache entry deserialization failed, entry ignored"](https://travis-ci.com/github/Pylons/pyramid_ldap/jobs/502857458#L248). I [cleared the cache](https://docs.travis-ci.com/user/caching#clearing-caches), and restarted the build. It still fails. I have no clue how to fix this, other than try moving it to GitHub Actions and forget about Travis.

2021-05-05 18:08 UTC, msander commented
Tests are passing now.

@bertjwregeer in setup.py, there is a comment ```'six',  # required by `ldappool` but not in their requirements file```
This seems still to be true and I think we should keep that requirement. Do you still want to remove the usage?

2021-05-05 21:42 UTC, stevepiercy approved these changes

2021-05-05 21:42 UTC, stevepiercy commented on tox.ini
> +    pip install -q pyramid_ldap[testing]
Nice catch!

2021-05-05 21:46 UTC, stevepiercy commented
> Tests are passing now.
> 
> @bertjwregeer in setup.py, there is a comment `` 'six', # required by `ldappool` but not in their requirements file ``
> This seems still to be true and I think we should keep that requirement. Do you still want to remove the usage?

I see [no instances of `six` in its code](https://opendev.org/openstack/ldappool/search?q=six), so maybe it is OK to remove? Please try and let's see what happens.

2021-05-05 22:07 UTC, msander commented
Please take a look at
https://opendev.org/openstack/ldappool/src/branch/master/ldappool/__init__.py

2021-05-05 23:49 UTC, bertjwregeer commented on setup.py
> +    'six',  # required by `ldappool` but not in their requirements file
If this is no longer required because `ldappool` itself is Py3 only and no longer uses `six` then let's remove this.

2021-05-05 23:53 UTC, bertjwregeer commented
> Please take a look at
> https://opendev.org/openstack/ldappool/src/branch/master/ldappool/__init__.py

I missed this... so then yes, keep the requirement for `six`.

2021-05-06 00:17 UTC, stevepiercy commented
@bertjwregeer I think this is OK to merge, unless you have any further review.

I can work on bringing it to Pylons Project standards and parity with Pyramid 2.0 for Python support and GHA later this week.

2021-05-10 02:21 UTC, merged